# Логирование — только важное
logging.level.com.example.demo=INFO
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN
logging.level.org.springframework.web=WARN
logging.level.org.springframework.security=WARN

# Яндекс OAuth
yandex.client-id=a791cf31c41c4c948106118d94548218
yandex.client-secret=7a6edfb9d35d437d9eece7f003fa1d5d
yandex.redirect-uri=https://ed-space.ru/api/auth/yandex/callback
yandex.token-url=https://oauth.yandex.ru/token
yandex.userinfo-url=https://login.yandex.ru/info

# VK OAuth
vk.client-id=54633568
vk.client-secret=l5DE1P3UOJQj1zXEK4Db
vk.redirect-uri=https://ed-space.ru/api/auth/vk/callback