# Логирование — только важное
logging.level.com.example.demo=INFO
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN
logging.level.org.springframework.web=WARN
logging.level.org.springframework.security=WARN